README.md

* Added a little clarification, what exactly this repo does.
* Formatted code-parts to be displayed as code (with backticks)
* Added complete example for running the image on a different port

Formatted README + added clarification

---

server.js

Been playing with a full swarm mode cluster using dind and want to be able to run visualizer at the host level but point it at a swarm manager using TCP daemon (on same network) rather than just `/var/run/docker.sock`. Can now pass in `-e DOCKER_HOST` in the same usual format <host>:<port> and visualizer will use that.
Usage now allows: `docker run -itd -p 8080:8080 -e HOST=localhost --net <my_swarm_network> -e DOCKER_HOST=<swarm_manager_host>:<swarm_manager_port> manomarks/visualizer`

Add TCP daemon support.

---

src/data-provider.js
src/main.js
src/vis-physical/index.js

Lock in container image title color, add a thing border with varied color. (See screenshot on Slack)
Convert some var to let.
Tested on Docker for Mac + Raspberry Pi

Change some function references to ES6 style.

---

src/data-provider.js

`docker node inspect` shows total memory available, not free memory. So label is changed from 'free' to 'RAM'.

Fix error with node memory labels

---

Dockerfile.aarch64

I just slightly modified the arm Dockerfile to make it run on my Pine64 card cluster.
Just changed to the frozeneye nodejs repository, so in essence it works exactly as arm arch.
To run it on dedicated hardware I build the container as:
```
docker $(docker-machine config pine64-1) build -f Dockerfile.aarch64 -t visualizer-aarch64 .
```
And I run it as:
```
docker $(docker-machine config pine64-1) run -it -d --privileged -p 8080:8080 -e HOST=pine64-1 -v /var/run/docker.sock:/var/run/docker.sock --name visualizer-aarch64_box visualizer-aarch64
```
Note the "--privileged" parameter, needed to overpass permissions problems
Hope it's helpful for anyone besides me

aarch64 Support

---

src/data-provider.js

It seems this matters only if you are running swarm nodes with much more memory, but the calculation from real bytes to display the "G RAM" seems wrong. It should divide by 1024 * 1024 * 1024 instead of 1000000000 to have Giga Bytes.
Using a packet.net ARMv8 machine with nominal 128GByte RAM shows 135 before the change:
Before:
Afterwards it shows 126 which seems correct as not all of the memory is available.
After:

Fix memory calculation to GByte

---

Dockerfile.windows
README.md

It is time to have the Docker Swarm Visualizer for Windows. Here is a Dockerfile to build the Visualizer in a Windows nanoserver.
To run it the Docker engine should additionally listen on port 2375, then run it from a PowerShell terminal
```powershell
$ip=(Get-NetIPAddress -AddressFamily IPv4 `
| Where-Object -FilterScript { $_.InterfaceAlias -Eq "vEthernet (HNS Internal NIC)" } `
).IPAddress
docker run -d -p 8080:8080 -e DOCKER_HOST=${ip}:2375 --name=visualizer stefanscherer/visualizer-windows
```

Add Dockerfile for Windows nanoserver

---

Dockerfile.windows
README.md
server.js

To work with a TLS secured Docker engine on Windows, set the environment variable `DOCKER_TLS_VERIFY` and bind mount the TLS certificates into the container.
```powershell
$ip=(Get-NetIPAddress -AddressFamily IPv4 `
| Where-Object -FilterScript { $_.InterfaceAlias -Eq "vEthernet (HNS Internal NIC)" } `
).IPAddress
docker run -d -p 8080:8080 -e DOCKER_HOST=${ip}:2376 -e DOCKER_TLS_VERIFY=1 -v "$env:USERPROFILE\.docker:C:\Users\ContainerAdministrator\.docker" --name=visualizer stefanscherer/visualizer-windows
```
Fixes #46

Use https.request if DOCKER_TLS_VERIFY env is set

---

Dockerfile
Dockerfile.aarch64

One of the problems I've seen using this images, especially important on aarch64, is that even the Dockerfile is based on official node slim image,the result is pretty thick. So I tried to move base images from Debian to Alpine, and the space reduction seems pretty nice to me, close 50%
Dockerfile 159 MB vs prior 371 MB
Dockerfile.aarch64 166 MB vs prior 317 MB
Dockerfile.aarch64 modifications are based on official 4.7-alpine node image. I just changed pgp server to mit.edu one because it's more reliable

Initial migration of Dockerfile and Dockerfile.aarch64 to Alpine

---

src/vis-physical/styles.less

hover adjusts to the size of the input, so long node names get displayed.

Adjusting CSS so that node-meta has a hover

---

Dockerfile.arm
README.md

Hi @ManoMarks 
I've done the following:
* Updated instructions
* Updated pushed ARM image to latest source code
* Added instructions for `docker swarm service create` on the RPi
Latest image on Hub - [tag 0.4](https://hub.docker.com/r/alexellis2/visualizer-arm/tags/)
Thanks,
Alex

Update ARM to Node 6.9 and latest source code

---

src/vis-physical/styles.less

position:absolute causes the node container to dodge the title block and throw off alignment

Fix repositioning bug on node title blocks

---

src/vis-physical/index.js
src/vis-physical/styles.less

onclick wasn't set-up and was resulting in errors.

Remoting onclick on containers which didn't do anything

---

README.md

The text and link where the other way around in the "Protect the Docker daemon socket" link

Fix url error.

---

server.js

I've tested Visualizer with Windows Server Insider 16278 and Docker 17.09.0-ce-rc2 which allows me to map the Windows named pipe `\\.\pipe\docker_engine` into a Windows container.
This is the equivalent to the Unix socket `/var/run/docker.sock`.
This PR adds the usage of the Windows named pipe if running on Windows.
My `Dockerfile.insider` to build the example image `stefanscherer/visualizer-windows:insider` that is also available on Docker Hub:
```Dockerfile
FROM stefanscherer/node-windows:8.4.0-insider
WORKDIR /app
ADD ./package.json /app/package.json
RUN npm install --unsafe-perm=true
ADD . /app
USER ContainerAdministrator
RUN npm run dist
ENV MS 200
EXPOSE 8080
CMD ["npm.cmd","start"]
```
After building the image and running it
```
docker run -v …
```

Use Windows named pipe

---

src/data-provider.js

Add the platform architecture/OS information to each node header in the
visualizer.
Signed-off-by: Phil Estes <estesp@gmail.com>
The actual code change adds this as line 177 of the modified file:
```
(currentnode.Description.Platform.Architecture) + "/" + (currentnode.Description.Platform.OS) + "<br/>";
```
but the rest of the changes are JS reformatting/cleanup by VSCode linter/editor plugin.

Add arch/os info to node header

---

src/data-provider.js
src/main.less
src/vis-physical/styles.less

Given UCP adds quite a few labels (and some of them quite long) to Swarm
nodes, I updated the font sizes of the various details about a node and
had overflow force wrapping on hover so that text doesn't go all over
the screen.
Signed-off-by: Phil Estes <estesp@gmail.com>
No need to merge unless others think this is reasonable; I'm going to use it privately at least for demos with UCP. Here's what it looks like with this PR applied to the visualizer:

Better CSS for labels/overflow on hover

---

src/utils/filter-containers.js
src/utils/request.js
src/vis-physical/index.js

This is a minor enhancement to my previous contribution. 
Now when you use the filter input, the browser history is updated (without a page refresh) with the properly URL-encoded text.
You can bookmark the new URL to essentially save filter states to quickly reference them in the future.
Here is a demo:

Sync filter options with URL parameter

---

src/data-provider.js

Timestamps with minute count lower than 10 should be zeropadded such that `19:6` becomes `19:06`.

Zeropad minutes

---

package.json

Reverts dockersamples/docker-swarm-visualizer#97 as Lodash 4.17.4 doesn't have findWhere

Revert "updating lodash to 4.17.4"

---

src/data-provider.js

Reverts dockersamples/docker-swarm-visualizer#94 because #99 reverted to an earlier version of Lodash. There are features lacking in Lodash 4.17.4 such as findWhere and bindAll that we don't have time to refactor for. If you want to zerpad the minutes please find another way

Revert "Zeropad minutes"

---

Dockerfile

Seemed node didn't like relative paths. Tried several things like `exec` mode for the CMD, and also tried`./healthcheck.js`, but it only seems to work as a healthcheck if full path is used.
Weird that `docker exec <containerid> node healthcheck.js` worked manually, so docker must be running the healthcheck slightly differently.
`¯\_(ツ)_/¯`

Fixes #68: failed healthchecks due to file path

---

README.md

Signed-off-by: Alex Ellis <alexellis2@gmail.com>
Hi Mano,
I wanted to raise this PR to update the references for the ARM image. It's easier if they both point to `latest` so I've written a small patch.
I also wanted to re-iterate that users can build this image themselves whenever they want a more up to date version. #101 
Keep up the great work - this is a very useful tool 👍 
Alex

Change tag 0.4 to latest for arm

---

package.json

Think this is responsible for breaking since `_.findWhere` isn't in 4.x lodash please can you revert?
Happy to help fixing and removing the dependency in slowertime
Looks like it repopens #98 though maybe different reasons
https://github.com/dockersamples/docker-swarm-visualizer/search?q=findwhere&unscoped_q=findwhere

Revert "updating package.json to remove another vulnerability"

---

src/data-provider.js

container and node display not work when container status is prepare, because there container object attribute equal null

fix containerId undefined

---

package.json
src/data-provider.js

Reintroduces bugfix #94 without upgrading Lodash as suggested in #100.

fix(data-provider): zeropad minutes

---

src/vis-physical/styles.less

Currently, if a cluster has a few nodes with a big number of containers, visualizer doesn't use the wide space correctly.
Was tested only on Chrome, so sorry if I'm missing something.

Wrap contents of nodes with multiple containers to fill wide screens

---

Dockerfile
package-lock.json
package.json

- Updated node 8 to 12. Yes that's still not current, but 14+ requires dep and code changes.
- Removed multi-stage and simplified dockerfile build
- Added package-lock.json
- Npm audit fix
- Added tini for starting node

node update, tini install, dockerfile style update

---

src/vis-physical/styles.less

After the last few PR's, a quirk showed up of container heights being too big when only a few containers are launched.

shrinking max box height
